#!/bin/bash

defoption=$(cat ~/.wp)

if [[ $1 == -* ]] ; then
    option=$1
    shift 
else
    option=$defoption
fi

case $option in 
    --firefox ) browser="firefox" ;;
    -f ) browser="firefox" ;;

    --chrome ) browser="google chrome" ;;
    -c ) browser="google chrome" ;;

    --opera ) browser="opera" ;;
    -o ) browser="opera" ;;

    -s ) browser="safari" ;;
    --safari ) browser="safari" ;;

    -p ) browser="SleipnirSE" ;;
    --sleipnir ) browser="SleipnirSE" ;;
esac

if [ $1 ] ; then url=$1 ; shift ; else url="" ; fi

if [ -z $url ] ; then
    open -a "$browser"
else
    if [[ $url != http* ]] ; then url=$(localurl $url) ; fi
    open -a "$browser" "$url"
fi
